--liquibase formatted sql
--changeset vulinh:002-use-sequences-and-create-dummy-data

ALTER TABLE author ALTER COLUMN id DROP IDENTITY;
CREATE SEQUENCE IF NOT EXISTS author_id_seq;
ALTER SEQUENCE author_id_seq OWNED BY author.id;
ALTER TABLE author ALTER COLUMN id SET DEFAULT nextval('author_id_seq');

ALTER TABLE book ALTER COLUMN id DROP IDENTITY;
CREATE SEQUENCE IF NOT EXISTS book_id_seq;
ALTER SEQUENCE book_id_seq OWNED BY book.id;
ALTER TABLE book ALTER COLUMN id SET DEFAULT nextval('book_id_seq');

INSERT INTO author (id, name)
VALUES (1, 'Jane Austen'),
       (2, 'George Orwell'),
       (3, 'J.R.R. Tolkien'),
       (4, 'Frank Herbert'),
       (5, 'Ursula K. Le Guin');

INSERT INTO book (id, title, author_id)
VALUES (1, 'Pride and Prejudice', 1),
       (2, 'Sense and Sensibility', 1),
       (3, 'Emma', 1),
       (4, '1984', 2),
       (5, 'Animal Farm', 2),
       (6, 'The Hobbit', 3),
       (7, 'The Fellowship of the Ring', 3),
       (8, 'The Two Towers', 3),
       (9, 'The Return of the King', 3),
       (10, 'Dune', 4),
       (11, 'Dune Messiah', 4),
       (12, 'Children of Dune', 4),
       (13, 'A Wizard of Earthsea', 5),
       (14, 'The Tombs of Atuan', 5),
       (15, 'The Farthest Shore', 5);

SELECT setval('author_id_seq', (SELECT MAX(id) FROM author), true);
SELECT setval('book_id_seq', (SELECT MAX(id) FROM book), true);

--rollback DELETE FROM book WHERE id BETWEEN 1 AND 15;
--rollback DELETE FROM author WHERE id BETWEEN 1 AND 5;
--rollback ALTER TABLE book ALTER COLUMN id DROP DEFAULT;
--rollback DROP SEQUENCE book_id_seq;
--rollback ALTER TABLE book ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
--rollback ALTER TABLE author ALTER COLUMN id DROP DEFAULT;
--rollback DROP SEQUENCE author_id_seq;
--rollback ALTER TABLE author ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
